[package]
distribution = "2201.11.0"
org = "ballerina"
name = "wsdltool"
version = "1.0.0"
authors = ["Ballerina"]
keywords = ["wsdl"]
repository = "https://github.com/ballerina-platform/wsdl-tools"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = false
