[tool]
id = "wsdl"

[[dependency]]
path = "lib/wsdl-cli-0.1.1-SNAPSHOT.jar"

[[dependency]]
path = "lib/wsdl-core-0.1.1-SNAPSHOT.jar"

[[dependency]]
path = "lib/wsdl4j-1.6.3.jar"

[[dependency]]
path = "lib/XmlSchema-1.4.7.jar"
